### ISSUE TITLE
Flight History 'close box background' disappears

### ISSUE THREAD

**Issue by B2VideoGames** [MegaphoneCA/xhauler#30]
Sometimes the Flight History 'close' box shows as grey, other times it isn't. 
I think the grey box is disappearing if you click anywhere else.

![Capture](https://user-images.githubusercontent.com/17802577/56061939-7ee10400-5d30-11e9-80d5-0ea66e3d97db.PNG)

**Comment by MegaphoneCA** [comment]
Confirmed

Intended behaviour being like the example shown
https://material.angular.io/components/button/overview

From
https://github.com/MegaphoneCA/xhauler/blob/master/client/src/app/flight-history-dialog/flight-history-dialog.component.html
```html
<mat-dialog-actions>
    <button mat-button [mat-dialog-close]>Close</button>
</mat-dialog-actions>
```

**Comment by MegaphoneCA** [comment]
It seems this is intended, part of the way angular works with the accessibility options is to always auto-select the 'close' button of any dialog component until another action is performed, so the user can easily dismiss a popup with a keypress
