### ISSUE TITLE
Person's State doesn't reflect Flight Training

### ISSUE THREAD

**Issue by B2VideoGames** [MegaphoneCA/XHauler#7]
During a flight training session, map showing new position and as 'in progress' but Pilot continues to show as 'idle'.

![capture2](https://user-images.githubusercontent.com/17802577/48215024-f3111900-e346-11e8-8a56-e099a45ec314.PNG)
![capture](https://user-images.githubusercontent.com/17802577/48215035-f4424600-e346-11e8-80b8-a0ae27939988.PNG)

**Comment by MegaphoneCA** [comment]
Fixed in latest build
