### ISSUE TITLE
[X-Plane] Crashing after 10-15 minutes of 'Flight Training'

### ISSUE THREAD

**Issue by MegaphoneCA** [MegaphoneCA/XHauler#8]
Please comment on this post with the following information

- Copy of your X-Plane log (X-Plane 11/Log.txt)
- Copy of XHauler plugin log (X-Plane 11/Resources/plugins/XHauler/xpnet.log)
- Airport departing from
- Brief description (i.e. flew north for 10 minutes then crash)

**Comment by B2VideoGames** [comment]
plane loaded/running at KBHM - just let the sim run after verifying it connected to Client (had to restart plugin once) never moved plane at all :: CTD after 20 min
[Log.txt](https://github.com/MegaphoneCA/XHauler/files/2563684/Log.txt)
[xpnet.log](https://github.com/MegaphoneCA/XHauler/files/2563685/xpnet.log)

**Comment by MegaphoneCA** [comment]
[Flight From DB](https://pastebin.com/LnpiXHhJ)

**Comment by MegaphoneCA** [comment]
(Didn't mean to close LOL)

**Comment by MegaphoneCA** [comment]
Opened an issue at XPNet for some insight / suggestions
https://github.com/jaurenq/XPNet/issues/11

**Comment by MegaphoneCA** [comment]
FINALLY reproduced it on my system
CYYC - CYXE 'Training Flight'
[xpnet.log](https://github.com/MegaphoneCA/XHauler/files/2564190/xpnet.log)
[Log.txt](https://github.com/MegaphoneCA/XHauler/files/2564191/Log.txt)
[DB Flight](https://pastebin.com/pxHH9Pq3)
